name: Linters
on:
  push:
    branches:
      - main
    paths:
      - "**"
  pull_request:
    paths:
      - "**"

defaults:
  run:
    shell: "bash"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16 # Need for npm >=7.7
          cache: "yarn"

      - name: Install yarn
        run: npm install -g yarn@1.22.17

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run lint
        run: yarn lint
