name: Tests
on:
  push:
    branches:
      - main
    paths:
      - "**"
  pull_request:
    paths:
      - "**"

defaults:
  run:
    shell: "bash"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install yarn
        run: npm install -g yarn@1.22.17

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run test:main:coverage
        run: yarn run test:main:coverage

  preload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install yarn
        run: npm install -g yarn@1.22.17

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run test:preload:coverage
        run: yarn test:preload:coverage

  renderer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install yarn
        run: npm install -g yarn@1.22.17

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run test:renderer:coverage
        run: yarn run test:renderer:coverage

  e2e:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install yarn
        run: npm install -g yarn@1.22.17

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Install chromium
        run: yarn playwright install --with-deps chromium

      - name: Run test:e2e
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- yarn run test:e2e
        if: matrix.os == 'ubuntu-latest'

      - name: Run test:e2e
        run: yarn run test:e2e
        if: matrix.os != 'ubuntu-latest'
