name: Tests
on:
  push:
    branches:
      - main
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

defaults:
  run:
    shell: 'bash'

jobs:

  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install yarn
        run: npm install -g yarn@1.22.17

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run test:main
        run: yarn run test:main


  preload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install yarn
        run: npm install -g yarn@1.22.17

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run test:preload
        run: yarn test:preload


  renderer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install yarn
        run: npm install -g yarn@1.22.17

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run test:renderer
        run: yarn run test:renderer


  e2e:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install yarn
        run: npm install -g yarn@1.22.17

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run test:main
        run: yarn run test:e2e
